"""
STOCHASTIC SAMPLING SETUP

Runs against the realistic MV/LV feeder (model_grid.py).
Formulates the Monte Carlo input distributions for a given target PV
penetration level:

  - PV size (installed/nameplate capacity, swept 0 to 2.5 MW):
        The "penetration level" is the total INSTALLED PV capacity target
        for the feeder -- what gets interconnected -- swept from 0 to
        2.5 MW per the proposal. "Bus" means the LV (0.4 kV) bus behind
        that node's distribution transformer -- the physically correct
        rooftop-PV interconnection point.
  - PV bus locations (spatial uncertainty):
        A random subset of candidate buses hosts the target capacity.
        Adoption fraction scales with how much of the WHOLE FEEDER's
        realistic ceiling the target represents (see sample_scenario).
  - Individual installation size (within a scenario):
        The scenario's total installed target is split unevenly across
        the adopting buses (random weights), then capped per bus at that
        bus's own realistic physical ceiling (a transformer/household
        cluster can't host more rooftop PV than its households could
        ever install) -- see sample_scenario for the redistribution
        logic and the "stress multiplier" that relaxes this cap in a
        controlled way when the target is deliberately swept past the
        whole feeder's realistic ceiling.
  - Time of day (drives BOTH irradiance and load -- temporal
    uncertainty):
        Each scenario represents one random hour, sampled from
        HOUR_WINDOW_MIN-HOUR_WINDOW_MAX (default 9:00-15:00 -- the
        midday "risk window" where reverse-power-flow risk concentrates,
        per the project's latest scope decision; widen back to (0, 24)
        if you want a full-day study instead). The 24-hour solar
        irradiance curve and residential demand curve are evaluated at
        that SAME hour, so they stay physically coupled.
  - Per-bus load variation (added realism):
        Real neighbouring transformers don't move in perfect lockstep.
        On top of the feeder-wide diurnal shape, each bus gets its own
        independent noise multiplier (PER_BUS_LOAD_NOISE_MIN/MAX) so load
        varies bus-to-bus, not just hour-to-hour.

sample_scenario() also accepts an optional `candidate_buses` override and
an optional `hour` override -- both added to support Phase 6's
stratified/conditional bus-wise study (main_buswise.py): the target bus
under test is held out and swept directly, while every OTHER bus gets a
realistic randomized "background" allocation generated by calling this
same function with candidate_buses restricted to exclude the target bus,
and hour forced to match the target bus's own sampled hour (so the whole
feeder shares one physically consistent clock per scenario).
"""

import math
import numpy as np
from model_grid import (
    CANDIDATE_PV_BUSES, TOTAL_PEAK_LOAD_KW, pv_max_kw_for_node,
    TOTAL_FEEDER_PV_CEILING_KW,
)

# ----------------------------------------------------------------------
# Distribution parameters (edit to match your exact assignment spec)
# ----------------------------------------------------------------------
PV_TOTAL_MIN_MW = 0.0
PV_TOTAL_MAX_MW = 2.5          # per proposal: "PV size (0 to 2.5 MW)"

# Spatial uncertainty: what fraction of candidate buses host PV in a given
# scenario. Scales with how close the target is to the whole feeder's
# realistic ceiling (see sample_scenario), with a floor and randomness
# layered on top.
ADOPTION_FRAC_FLOOR = 0.85
ADOPTION_FRAC_NOISE_MIN = 0.95
ADOPTION_FRAC_NOISE_MAX = 1.05

# Individual installation size variability (how unevenly the scenario's
# total target is split across adopting buses). Higher = more variable.
SIZE_VARIABILITY_CV = 0.15

# Demand variability layered on top of the diurnal shape below (day-to-day
# randomness at the FEEDER level -- not every day looks like the
# "typical" curve).
LOAD_NOISE_MIN = 0.85
LOAD_NOISE_MAX = 1.15

# Per-BUS load variability, layered on top of the feeder-wide load noise
# above, so neighbouring transformers don't move in perfect lockstep.
PER_BUS_LOAD_NOISE_MIN = 0.85
PER_BUS_LOAD_NOISE_MAX = 1.15

# Time window the Monte Carlo scenarios are drawn from. Restricted to the
# midday "risk window" (high solar, moderate-to-low demand) by default --
# this concentrates every scenario into the hours that actually matter for
# reverse-power-flow risk, instead of diluting the sample with night
# hours that trivially show zero PV output. NOTE: this changes what the
# reported violation probability means -- "probability of violation
# during peak solar hours," not "probability across a representative
# full day." State this scope explicitly in your report. Set back to
# (0.0, 24.0) for a full-day study.
HOUR_WINDOW_MIN = 9.0
HOUR_WINDOW_MAX = 15.0


# ----------------------------------------------------------------------
# Diurnal profiles
# ----------------------------------------------------------------------
# Solar irradiance: a clear-sky bell curve, zero before sunrise (06:00)
# and after sunset (18:00), peaking at solar noon. This models Dhaka's
# approximate day length; if your course specifies exact sunrise/sunset
# times or a measured irradiance dataset, swap this function out.
SUNRISE_HOUR = 6.0
SUNSET_HOUR = 18.0


def irradiance_factor(hour):
    """
    Clear-sky irradiance factor (0 to 1) at a given hour of day (0-24,
    can be fractional). Zero outside daylight hours; a half-sine shape
    (a standard simple clear-day approximation) peaking at 1.0 at solar
    noon.
    """
    if hour <= SUNRISE_HOUR or hour >= SUNSET_HOUR:
        return 0.0
    day_length = SUNSET_HOUR - SUNRISE_HOUR
    return max(0.0, math.sin(math.pi * (hour - SUNRISE_HOUR) / day_length))


# Representative residential/mixed demand shape: low overnight, a mild
# morning bump, a midday trough (people at work/school), ramping up to
# the evening peak, per the proposal's "24-hour residential/mixed curve
# capturing morning/evening peaks and midday troughs." These are
# illustrative anchor points, not a measured Dhaka load dataset -- swap
# in real utility data here if you have it for your final submission.
_LOAD_ANCHOR_HOURS = [0, 3, 6, 9, 12, 15, 18, 21, 24]
_LOAD_ANCHOR_VALS = [0.42, 0.40, 0.55, 0.85, 0.65, 0.68, 0.78, 1.00, 0.42]


def load_diurnal_factor(hour):
    """Demand multiplier (roughly 0.4-1.0) at a given hour of day."""
    return float(np.interp(hour, _LOAD_ANCHOR_HOURS, _LOAD_ANCHOR_VALS))


def sample_scenario(rng, pv_total_target_mw, candidate_buses=None, hour=None):
    """
    Draw one Monte Carlo scenario for a given target INSTALLED PV
    penetration (aggregate nameplate capacity, in MW).

    Parameters
    ----------
    rng : numpy.random.Generator
        Seeded RNG (share one rng across a whole study run for
        reproducibility).
    pv_total_target_mw : float
        Target aggregate INSTALLED PV capacity for this scenario
        (0 to PV_TOTAL_MAX_MW, per the proposal's stated PV size range).
    candidate_buses : list of int, optional
        Which buses may adopt PV in this scenario. Defaults to
        CANDIDATE_PV_BUSES (every bus on the feeder). Phase 6's bus-wise
        study passes a restricted list (every bus EXCEPT the one under
        test) to generate a realistic "background" allocation alongside
        a directly-controlled target bus.
    hour : float, optional
        Force this scenario to a specific hour of day (0-24) instead of
        drawing a random one. Used by Phase 6 so a scenario's background
        allocation shares the exact same clock as its target-bus
        injection -- one feeder, one time of day, always.

    Returns
    -------
    pv_installed_mw : dict {bus_number: installed_nameplate_MW}
        Empty dict if pv_total_target_mw == 0.
    pv_actual_mw : dict {bus_number: actual_output_MW}
        Same buses as pv_installed_mw, scaled by this scenario's
        irradiance factor -- THIS is what gets injected into the power
        flow, never the raw nameplate value.
    per_bus_load_scale : dict {bus_number: float}
        This scenario's load multiplier for EVERY candidate bus on the
        whole feeder (not just the ones in `candidate_buses` above --
        load scaling applies to every household cluster regardless of
        whether that bus is allowed to host PV in this call). Feeder-wide
        diurnal shape x feeder-wide noise x this bus's own independent
        noise.
    hour : float
        The hour of day (0-24) used for this scenario (either the one
        you passed in, or the one randomly drawn).
    """
    if candidate_buses is None:
        candidate_buses = CANDIDATE_PV_BUSES

    if hour is None:
        hour = rng.uniform(HOUR_WINDOW_MIN, HOUR_WINDOW_MAX)
    irr = irradiance_factor(hour)

    feeder_load_noise = rng.uniform(LOAD_NOISE_MIN, LOAD_NOISE_MAX)
    base_load_scale = load_diurnal_factor(hour) * feeder_load_noise
    per_bus_load_scale = {
        bus: base_load_scale * rng.uniform(PER_BUS_LOAD_NOISE_MIN, PER_BUS_LOAD_NOISE_MAX)
        for bus in CANDIDATE_PV_BUSES
    }

    if pv_total_target_mw <= 0:
        return {}, {}, per_bus_load_scale, hour

    n_candidates = len(candidate_buses)

    # Adoption fraction scales with how much of the WHOLE FEEDER's
    # realistic ceiling this target represents -- a low target is
    # plausibly met by a handful of early adopters; a target approaching
    # the feeder's full realistic ceiling can only be met if most/all
    # buses have adopted.
    target_frac_of_ceiling = min(1.0, pv_total_target_mw * 1000.0 / TOTAL_FEEDER_PV_CEILING_KW)
    adopt_frac = np.clip(target_frac_of_ceiling * rng.uniform(ADOPTION_FRAC_NOISE_MIN, ADOPTION_FRAC_NOISE_MAX),
                          ADOPTION_FRAC_FLOOR, 1.0)
    n_adopt = max(1, min(n_candidates, int(round(adopt_frac * n_candidates))))
    adopting_buses = rng.choice(candidate_buses, size=n_adopt, replace=False)

    weights = rng.gamma(shape=1.0 / SIZE_VARIABILITY_CV**2, scale=1.0, size=n_adopt)
    weights = weights / weights.sum()
    sizes_mw = weights * pv_total_target_mw

    pv_installed_mw = {int(bus): float(size) for bus, size in zip(adopting_buses, sizes_mw)}

    # Physical cap: a single node's distribution transformer can't host
    # more rooftop PV than its own household count could ever install --
    # e.g. a 45-household node with a 100kVA transformer cannot physically
    # receive several hundred kW just because the feeder-wide random split
    # happened to assign it that much. Without this cap, an aggregate
    # target that's easy for the FEEDER as a whole can still be physically
    # impossible for one specific node, producing meaningless transformer
    # overloads that reflect a modeling artifact, not a real finding.
    #
    # The cap itself scales with a "stress multiplier": at or below the
    # whole feeder's realistic ceiling (TOTAL_FEEDER_PV_CEILING_KW, i.e.
    # every household at PV_MAX_KW_PER_HOUSEHOLD), each bus is capped at
    # its own true realistic ceiling -- no bus can be forced beyond what
    # its households could plausibly install. But if pv_total_target_mw
    # is deliberately swept PAST the whole feeder's realistic ceiling (a
    # stress test), the per-bus cap scales up proportionally too, so the
    # study can still find the technical violation threshold beyond
    # today's realistic adoption policy.
    stress_multiplier = max(1.0, pv_total_target_mw * 1000.0 / TOTAL_FEEDER_PV_CEILING_KW)

    for _ in range(3):
        excess_mw = 0.0
        headroom = {}
        for bus, size in pv_installed_mw.items():
            ceiling_mw = (pv_max_kw_for_node(bus) * stress_multiplier) / 1000.0
            if size > ceiling_mw:
                excess_mw += size - ceiling_mw
                pv_installed_mw[bus] = ceiling_mw
                headroom[bus] = 0.0
            else:
                headroom[bus] = ceiling_mw - size
        total_headroom = sum(headroom.values())
        if excess_mw <= 1e-9 or total_headroom <= 1e-9:
            break
        for bus, room in headroom.items():
            if room > 0:
                pv_installed_mw[bus] += excess_mw * (room / total_headroom)

    pv_actual_mw = {bus: size * irr for bus, size in pv_installed_mw.items()}
    return pv_installed_mw, pv_actual_mw, per_bus_load_scale, hour


if __name__ == "__main__":
    rng = np.random.default_rng(42)

    print("=== Phase 2 validation: diurnal curves (within the 9:00-15:00 risk window) ===\n")
    print(f"{'Hour':>5} {'Irradiance':>11} {'Load factor':>12}")
    for h in np.arange(HOUR_WINDOW_MIN, HOUR_WINDOW_MAX + 0.1, 1.0):
        print(f"{h:>5.1f} {irradiance_factor(h):>11.3f} {load_diurnal_factor(h):>12.3f}")

    print(f"\nFeeder peak load: {TOTAL_PEAK_LOAD_KW:.1f} kW")
    print(f"Candidate PV buses ({len(CANDIDATE_PV_BUSES)}): {CANDIDATE_PV_BUSES}")
    print(f"Whole-feeder realistic PV ceiling: {TOTAL_FEEDER_PV_CEILING_KW:.0f} kW "
          f"({TOTAL_FEEDER_PV_CEILING_KW/1000:.2f} MW)")
    print(f"PV installed-capacity range: {PV_TOTAL_MIN_MW}-{PV_TOTAL_MAX_MW} MW\n")

    for pv_target in [0, 0.5, 1.25, 2.5]:
        print(f"--- Target installed capacity: {pv_target} MW ---")
        for i in range(4):
            pv_inst, pv_act, load_scale, hour = sample_scenario(rng, pv_target)
            total_inst = sum(pv_inst.values())
            total_act = sum(pv_act.values())
            print(f"  scenario {i}: hour={hour:5.2f}, irr={irradiance_factor(hour):.3f}, "
                  f"{len(pv_inst)} buses, installed={total_inst:.3f} MW, "
                  f"actual output={total_act:.3f} MW, "
                  f"load_scale range=[{min(load_scale.values()):.3f}, {max(load_scale.values()):.3f}]")
        print()

    print("--- Background-allocation call (Phase 6 style: bus 12 excluded, shared hour) ---")
    other_buses = [b for b in CANDIDATE_PV_BUSES if b != 12]
    pv_inst, pv_act, load_scale, hour = sample_scenario(rng, 1.0, candidate_buses=other_buses, hour=11.5)
    print(f"hour forced to {hour}, bus 12 excluded: {12 not in pv_inst}")
    print(f"buses used: {sorted(pv_inst.keys())}")
